### ISSUE TITLE
Question about reverse proxy

### ISSUE THREAD

**Issue by teate** [pdevito3/StandaloneBffExampleFrontend#1]
Hi.

I got the example working, thanks for that! However, I think it is crucial to think a way of getting this setup working also in production environments. Do you happen to know, if this separate domain approach is possible for example like so that UI is running on ui.example.com and the BFF in bff.example.com? 

I'm not sure if that reduces the security somehow? But I guess if you'd have the reverse proxy in the middle, it shouldn't? Well, I think the BFF is nice security approach for securing SPA, but there are quite little of information how to achieve this architecture. 

So my question is that could this be solved when using the BFF with the YARP? Or does it still need completely separate reverse proxy, which is outside of the BFF? Simply put: ui.example.com -> proxy.example.com -> bff-example.com? Sorry I'm not that familiar with the reverse-proxying so hard to write any good examples.

I'm not expecting any specific walkthrough type of answers, but I just want to say out loud that I'm surprised how little of information there is for this exact architecture. And I think this would be hugely appreciated blog topic.

**Comment by pdevito3** [comment]
I wouldn't expect this model to be an issue from a security perspective. There might be some settings to keep in mind with something like this, but it's all really just an infra question I would think. Not my depth so can't speak to it with much authority at the moment. 

I know the team is talking about adding some stuff to the docs. https://github.com/DuendeSoftware/docs.duendesoftware.com/issues/227

**Comment by teate** [comment]
Thanks for the link. Yea I've been pondering if this could be possible with the BFF's own reverse proxy. So that there isn't any additional reverse proxy there, but its own. But I stay tuned if there are any examples made in coming months. Kinda surprised to be honest that the SPA -> BFF -> API architecture is now the somewhat recommended way to authenticate the SPA, but there is so little of actual examples how to implement that. Especially those, that are not forcing you to couple the SPA with the dotnet bff so tightly. But nevertheless, thanks for your answer.
